const express = require('express')
const ejs = require('ejs')
const mongoose = require('mongoose')
const newPostController = require('./controllers/newPost')
const homePageController = require('./controllers/home')
const getPostController = require('./controllers/getPost')
const storePostController = require('./controllers/storePost')
const newUserController = require('./controllers/newUser')
const storeUserController = require('./controllers/storeUser')
const loginController = require('./controllers/login')
const loginUserController = require('./controllers/loginUser')
const validateController = require('./middleware/validationMiddleware')
const bodyParser = require('body-parser')
const fileUpload = require('express-fileupload')
mongoose.connect('mongodb+srv://sgupta3:sgupta3@testcluster.d1ccdlt.mongodb.net/myFirstDatabase1?retryWrites=true&w=majority',{useNewUrlParser: true})
const app = new express()
app.use(express.static('public'))
app.set('view engine', 'ejs')
app.use(fileUpload())
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({extended:true}))
app.use('/posts/store',validateController)
app.listen(3500, () => {
    console.log('App listening on port 3500')
})
app.get('/', homePageController)
app.post('/posts/store',storePostController)
app.get('/post/new',newPostController)
app.get('/post/:id',getPostController)
app.get('/auth/register',newUserController)
app.post('/user/register',storeUserController)
app.get('/auth/login',loginController)
app.post('/user/login',loginUserController)